### ISSUE TITLE
Nice but not responsive both orients of my phone

### ISSUE THREAD

**Issue by martinmurciego** [loebi-ch/jquery-clock-timepicker#7] opened 2017-12-19 21:06 UTC
Android

**Comment by martinmurciego** [comment] 2017-12-19 21:07
Android 5.1.1 
Chrome

**Comment by loebi-ch** [comment] 2017-12-19 22:40
Hi Martin

You're absolutely right. I rarely use my mobile phone in the landscape orientation that's why I haven't realized it. I'm going to fix that issue in the next release, but probably this will not be before mid of January 2018.

Thank you for your valuable comment.

Best regards,
Andy

**Comment by martinmurciego** [comment] 2017-12-19 23:31
My phone has a 4-inch screen. And the photo if it can be visualized is in vertical. I just wanted to give a contribution. Thank you.
![phone-vertical-4inch-android-5 1 1](https://user-images.githubusercontent.com/7759127/34183750-1b26690e-e4fb-11e7-8148-5f77015cef68.png)

**Comment by loebi-ch** [comment] 2017-12-21 18:40
Puhhh...
that's really strange. I cannot reproduce this issue in portrait mode on my available mobile phones and neither with any emulator. I hope I find some time in January to have a deeper look at it.

Any other guys facing this issue and can give me some clue?

**Comment by reclaimingmytime** [comment] 2018-02-06 09:22
I believe the issue is that the plugin only takes account of the width, but not the height of the device. Therefore, the clock only fits on the screen if the device is tall enough, which is most of the time not the case in landscape mode.

The following screenshots were taken on a 5.5-inch 1080p phone.
Here is an example in portrait mode:
![portrait](https://user-images.githubusercontent.com/35609464/35851175-7b2505ca-0b27-11e8-931b-856e46f06842.jpg)
And here is an example in landscape mode:
![landscape](https://user-images.githubusercontent.com/35609464/35851192-84c5a13e-0b27-11e8-95de-9c74e358f2db.jpg)

I hope that helps.

**Comment by loebi-ch** [comment] 2018-02-06 21:34
Thank you for your input @reclaimingmytime.

It's definitely true that this plugin does not work in landscape mode because it only takes account of the width and not of the height, as you've mentioned. I think I find some time soon to fix this.

Concerning the problem in the portrait mode as mentioned by @martinmurciego:
Recently I observed the same behavior. The problem for me was that my website was not yet responsive (the content was too wide) and the clock time picker popup was to wide as well. After some investigation I found out that I take the wrong width - the width of the document instead of the width of the viewport. The point that I don't understand: You observed this behavior on my example page, but this page is fully responsive...?!

I'm going to replace the width by the viewport width and take into account the height to make sure that it will also work in landscape mode. I hope this implementation will fix all your issues.

Thank you for your patience.

Andy

**Comment by loebi-ch** [comment] 2018-02-06 22:33
@martinmurciego and @reclaimingmytime, I think I fixed it:

Check out the example page http://plugins.slyweb.ch/jquery-clock-timepicker and give me some feedback.

In landscape mode the clock time picker popup is quite small and if the browser toolbar is visible there is even less space. I have to make the paddings & margins less... I'll finish that by the end of the week.

(I haven't published an update yet)

**Comment by reclaimingmytime** [comment] 2018-02-07 07:59
Thank you for working on a fix. Looks a lot better now.

Additionally to (or instead of) tweaking the margin and padding, you could change the font size of the digital clock on smaller screens or show the digital clock next to the left side of the analog clock. The latter is what the default Android time switcher does in landscape mode. But I don't know if that is possible with the current setup, so changing the margin might be the easiest solution.

**Comment by loebi-ch** [comment] 2018-02-07 10:25
Thank you @reclaimingmytime for you precious input about placing digital and analog clock side by side.

The jquery-clock-timepicker now works in portrait and landscape mode, so I close this issue.

Make sure to use the newest version 2.2.0+.

**Closed as completed by loebi-ch** 2018-02-07 10:25 UTC

**Comment by reclaimingmytime** [comment] 2018-02-07 13:22
Thank you for fixing the issue.

I am glad I could be of help.
